2019-09-25 18:43:50.332 [ERR] [session.go:253] recvLoop error: read tcp 127.0.0.1:17000->127.0.0.1:58686: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:58686, sessionid: 1, localAddr: 127.0.0.1:17000
2019-09-25 18:43:50.38 [ERR] [session.go:265] read and handle message error: read tcp 127.0.0.1:17000->127.0.0.1:58686: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:58686,  localAddr: 127.0.0.1:17000, sessionid: 1
2019-09-25 18:43:50.419 [ERR] [Entity.go:599] AsyncCall service not exist: 39,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-09-25 18:45:15.885 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-09-25 18:45:15.89 [ERR] [Entity.go:600] AsyncCall service not exist: 39,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-09-25 18:46:45.217 [ERR] [session.go:253] recvLoop error: read tcp 127.0.0.1:17000->127.0.0.1:53945: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:53945, sessionid: 1, localAddr: 127.0.0.1:17000
2019-09-25 18:46:45.218 [ERR] [session.go:265] read and handle message error: read tcp 127.0.0.1:17000->127.0.0.1:53945: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:53945,  localAddr: 127.0.0.1:17000, sessionid: 1
2019-09-25 18:46:45.232 [ERR] [Entity.go:600] AsyncCall service not exist: 39,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-09-25 18:47:25.49 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-09-25 18:47:25.493 [ERR] [Entity.go:600] AsyncCall service not exist: 39,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-09-25 18:48:16.847 [ERR] [session.go:253] recvLoop error: read tcp 127.0.0.1:17000->127.0.0.1:54009: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:54009, sessionid: 1, localAddr: 127.0.0.1:17000
2019-09-25 18:48:16.848 [ERR] [session.go:265] read and handle message error: read tcp 127.0.0.1:17000->127.0.0.1:54009: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:54009,  localAddr: 127.0.0.1:17000, sessionid: 1
2019-09-25 18:48:16.863 [ERR] [Entity.go:600] AsyncCall service not exist: 39,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-09-25 18:49:23.293 [ERR] [msghdl.go:54] handle msg is panic:1aaaasdsdsaaagoroutine 67 [running]:
runtime/debug.Stack(0xc0002b7750, 0xab4e20, 0xc91970)
	D:/Go/src/runtime/debug/stack.go:24 +0xa4
gitlab.ztgame.com/tech/public/go-service/zeus/base/net/internal/internal/msghdl.(*MessageHandler).HandleRawMsg.func1(0xc0002b0001)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/base/net/internal/internal/msghdl/msghdl.go:53 +0x5e
panic(0xab4e20, 0xc91970)
	D:/Go/src/runtime/panic.go:522 +0x1c3
gitlab.ztgame.com/tech/public/go-service/zeus/framework/entity.(*Entity).OnEntityCreated(0xc00004ef00, 0x1, 0xbaf4fc, 0x6, 0x0, 0xbab960, 0xc00004ef00, 0xcb8be0, 0xc0001002c0, 0xa97b20, ...)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/framework/entity/Entity.go:217 +0x40
gitlab.ztgame.com/tech/public/go-service/zeus/framework/entity.(*Entities).CreateEntityWithID(0xc0001002c0, 0xbaf4fc, 0x6, 0x1, 0x0, 0xa97b20, 0xc0000e8b20, 0xc0002b7901, 0x0, 0x20, ...)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/framework/entity/Entities.go:158 +0x26e
gitlab.ztgame.com/tech/public/go-service/zeus/logic/gatewaybase/proc.(*PGatewayServer).MsgProcLoginReq(0xc000100500, 0xc0000e0630)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/logic/gatewaybase/proc/ProcGateway.go:118 +0x806
reflect.Value.call(0xb167e0, 0xc000100500, 0x613, 0xbadc38, 0x4, 0xc0002b7e28, 0x1, 0x1, 0x1, 0x11a0ff0, ...)
	D:/Go/src/reflect/value.go:447 +0x468
reflect.Value.Call(0xb167e0, 0xc000100500, 0x613, 0xc0002b7e28, 0x1, 0x1, 0x0, 0x0, 0x11b0080)
	D:/Go/src/reflect/value.go:308 +0xab
gitlab.ztgame.com/tech/public/go-service/zeus/base/net/internal/internal/msghdl.(*MessageHandler).HandleRawMsg(0xc0000f4558, 0x2540b0001, 0xc0000fc2a2, 0xf, 0xf)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/base/net/internal/internal/msghdl/msghdl.go:79 +0x34d
gitlab.ztgame.com/tech/public/go-service/zeus/base/net/internal/internal.(*Session).readAndHandleOneMsg(0xc0002ae000, 0xc0001405a0, 0x0)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/base/net/internal/internal/session.go:446 +0x41c
gitlab.ztgame.com/tech/public/go-service/zeus/base/net/internal/internal.(*Session).recvLoop(0xc0002ae000)
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/base/net/internal/internal/session.go:247 +0x7a
created by gitlab.ztgame.com/tech/public/go-service/zeus/base/net/internal/internal.(*Session).Start
	C:/Users/yekoufeng/go/pkg/mod/gitlab.ztgame.com/tech/public/go-service/zeus@v0.0.19/base/net/internal/internal/session.go:110 +0x62

2019-09-25 18:49:23.293 [ERR] [session.go:253] recvLoop error: Session verification failed, remoteAddr: 127.0.0.1:54090, sessionid: 1, localAddr: 127.0.0.1:17000
2019-09-25 18:49:23.295 [ERR] [session.go:265] read and handle message error: Session verification failed, remoteAddr: 127.0.0.1:54090,  localAddr: 127.0.0.1:17000, sessionid: 1
2019-09-25 18:50:19.097 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-09-25 18:50:19.101 [ERR] [Entity.go:600] AsyncCall service not exist: 39,  sType: 3 ,methodName: SyncEntitySrvInfo
