2019-10-08 18:02:41.718 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-10-08 18:02:41.721 [ERR] [Entity.go:599] AsyncCall service not exist: 83,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-10-08 18:02:46.731 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-10-08 18:02:46.735 [ERR] [localService.go:273] processCall, entity not exist,methodName: LeaveTeam, groupID: 0, entityID: 1
2019-10-08 18:06:18.829 [ERR] [session.go:253] recvLoop error: read tcp 127.0.0.1:17000->127.0.0.1:52932: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:52932, sessionid: 1, localAddr: 127.0.0.1:17000
2019-10-08 18:06:18.83 [ERR] [session.go:265] read and handle message error: read tcp 127.0.0.1:17000->127.0.0.1:52932: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:52932,  localAddr: 127.0.0.1:17000, sessionid: 1
2019-10-08 18:08:01.669 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-10-08 18:08:06.682 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-10-08 18:08:06.686 [ERR] [localService.go:273] processCall, entity not exist,methodName: LeaveTeam, groupID: 0, entityID: 1
2019-10-08 18:08:56.777 [ERR] [session.go:253] recvLoop error: read tcp 127.0.0.1:17000->127.0.0.1:53321: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:53321, sessionid: 1, localAddr: 127.0.0.1:17000
2019-10-08 18:08:56.779 [ERR] [session.go:265] read and handle message error: read tcp 127.0.0.1:17000->127.0.0.1:53321: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:53321,  localAddr: 127.0.0.1:17000, sessionid: 1
2019-10-08 18:09:01.719 [ERR] [arq_listener.go:151] accept connection error accept tcp [::]:17000: use of closed network connection
2019-10-08 18:09:01.723 [ERR] [arq_listener.go:151] accept connection error accept tcp 127.0.0.1:17010: use of closed network connection
2019-10-08 18:09:47.921 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-10-08 18:09:47.924 [ERR] [Entity.go:599] AsyncCall service not exist: 3,  sType: 3 ,methodName: SyncEntitySrvInfo
2019-10-08 18:09:52.935 [ERR] [mongodboperate.go:89] session nil, not connect or auth
2019-10-08 18:09:52.94 [ERR] [localService.go:273] processCall, entity not exist,methodName: LeaveTeam, groupID: 0, entityID: 1
